### PR TITLE
Microverse - Ruby Project - Enumerables

### PR DESCRIPTION
**Pull request by jmontanholi**
## In this feature branch we did the following implementations:
  - my_each and my_each_with_index code
  - my_select code
  - my_all? code
  - my_any? code
  - my_none? code
  - my_count code
  - my_map code
  - my_injec code
  - multiply_els code

### CODE REVIEW

**Review by bini-i — CHANGES_REQUESTED** [review]
# Status: Changes requred :yellow_circle:  
### Hello  team :wave: 

#### Your project is starting to look good but you must work on all requirements listed below to successfully implement enumerable methods:

### README
- Please illustrate how to use your enumerable methods locally.

### my_each
- returns an Enumerator if no block is given
- when a block is given when self is an array returns the array itself after calling the given block once for each element in self
- when a block is given when self is a range returns the range itself after calling the given block once for each element in self
- when a block is given when self is a range behaves like #each calls the given block once for each element in self
- when a block is given when self is a hash behaves like #each calls the given block once for each element in self
### my_each_with_index
- returns an enumerator if no block is given
- when a block is given when self is an array returns the array itself after calling the given block once for each element in self
- when a block is given when self is a range returns the range itself after calling the given block once for each element in self
- when a block is given when self is a range behaves like #each_with_index calls the given block once for each element in self
- when a block is given when self is a hash behaves like #each_with_index calls the given block once for each element in self
### my_select
- returns an array containing all elements of enum for which the given block returns a true value::range
- returns an enumerator if no block is given
### my_all?
- returns false if the block returns false or nil::range
- when no block or argument is given returns true when none of the collection members are false or nil
- when no block or argument is given returns false when one of the collection members are false or nil
- when a class is passed as an argument returns true if all of the collection is a member of such class::Integer
- when a class is passed as an argument returns true if all of the collection is a member of such class::Numeric
- when a class is passed as an argument returns false if any of the collection is not a member of such class
- when a Regex is passed as an argument returns true if all of the collection matches the Regex
- when a Regex is passed as an argument returns false if any of the collection does not match the Regex
- when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern
- when a pattern other than Regex or a Class is given returns false if any of the collection does not match the pattern
### my_any?
- returns false if the block ever returns a value false or nil::range
- when no block or argument is given returns true if at least one of the collection is not false or nil
- when no block or argument is given returns false if at least one of the collection is not true
- when a class is passed as an argument returns true if at least one of the collection is a member of such class::Numeric
- when a class is passed as an argument returns true if at least one of the collection is a member of such class::Integer
- when a Regex is passed as an argument returns true if any of the collection matches the Regex
- when a Regex is passed as an argument returns false if none of the collection matches the Regex
- when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern
- when a pattern other than Regex or a Class is given returns true if any of the collection matches the pattern
### my_none?
- returns false if the block ever returns true for all elements::range
- when no block or argument is given returns true only if none of the collection members is true
- when no block or argument is given returns false only if one of the collection members is true
- when a class is passed as an argument returns true if none of the collection is a member of such class
- when a class is passed as an argument returns true if none of the collection is a member of such class::Numeric
- when a class is passed as an argument returns false if any of the collection is a member of such class
- when a Regex is passed as an argument returns true if none of the collection matches the Regex
- when a Regex is passed as an argument returns false if any of the collection matches the Regex
- when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern
- when a pattern other than Regex or a Class is given returns false only if one of the collection matches the pattern
### my_count
- returns the number of items in enum through enumeration::range
### my_map
- returns a new array with the results of running a given block once for every element in enum::range
- returns an Enumerator if no block is given
- executes only the proc when both a block and a proc are given and returns a new array with the results of running the proc once for every element in enum.
### my_inject
- searches for the longest word in an array of strings
- when a block is given without an initial value combines all elements of enum by applying a binary operation, specified by a block::range
- when a block is given with an initial value combines all elements of enum by applying a binary operation, specified by a block
- when a symbol is specified without an initial value combines each element of the collection by applying the symbol as a named method
- when a symbol is specified without an initial value combines each element of the collection by applying the symbol as a named method:range
- when a symbol is specified with an initial value combines each element of the collection by applying the symbol as a named method
- when a symbol is specified with an initial value combines each element of the collection by applying the symbol as a named method::range
### multiply_els
- accepts an array as an argument and multiplies all the elements of the array together using #my_inject

#### If you have any question kindly reach me on slack @Binyam Hailemeskel

### HAPPY CODING :computer: :blush: 

> #### Reviewed by Binyam Hailemeskel (TSE)
> GitHub: [@bini-i](https://github.com/bini-i)
> Twitter: [@binyamshewa](https://twitter.com/binyamshewa)
> LinkedIn: [LinkedIn](https://www.linkedin.com/in/binyam-hailemeskel-728048151/)

**Review by GzimAsani — CHANGES_REQUESTED** [review]
# STATUS: Changes Required :red_circle: 

### Hello team, good job implementing the changes asked from the previous reviewer :muscle: but unfortunately some of your methods are not working as expected and we still have work to do in order to complete all the requirements. Please check below the required changes:
### **my_each**
- [x] returns an Enumerator if no block is given
- [x] when a block is given when self is a range returns the range itself after calling the given block once for each element in self
- [x] when a block is given when self is a range behaves like #each calls the given block once for each element in self
### **my_each_with_index**
- [x] returns an enumerator if no block is given
- [x] when a block is given when self is a range returns the range itself after calling the given block once for each element in self
- [x] when a block is given when self is a range behaves like #each_with_index calls the given block once for each element in self
- [x] when a block is given when self is a hash behaves like #each_with_index calls the given block once for each element in self
### **my_select**
- [x] returns an enumerator if no block is given
### **my_all**
- [x] returns false if the block returns false or nil::range
- [x] when no block or argument is given returns true when none of the collection members are false or nil
- [x] when no block or argument is given returns false when one of the collection members are false or nil
- [x] when a class is passed as an argument returns true if all of the collection is a member of such class::Integer
- [x] when a class is passed as an argument returns true if all of the collection is a member of such class::Numeric
- [x] when a class is passed as an argument returns false if any of the collection is not a member of such class
- [x] when a Regex is passed as an argument returns true if all of the collection matches the Regex
- [x] when a Regex is passed as an argument returns false if any of the collection does not match the Regex
- [x]  when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern
- [ ]  when a pattern other than Regex or a Class is given returns false if any of the collection does not match the pattern

### **my_any**
- [x] when no block or argument is given returns false if at least one of the collection is not true
- [x] returns false if the block ever returns a value false or nil::range
- [x] when no block or argument is given returns true if at least one of the collection is not false or nil
- [x] when no block or argument is given returns false if at least one of the collection is not true
- [x] when a class is passed as an argument returns true if at least one of the collection is a member of such class::Numeric
- [x] when a class is passed as an argument returns true if at least one of the collection is a member of such class::Integer
- [x] when a Regex is passed as an argument returns true if any of the collection matches the Regex
- [x] when a Regex is passed as an argument returns false if none of the collection matches the Regex
- [ ] when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern
- [ ] when a pattern other than Regex or a Class is given returns true if any of the collection matches the pattern

### **my_none**
- [x] returns false if the block ever returns true for all elements::range
- [x] when no block or argument is given returns true only if none of the collection members is true
- [x] when no block or argument is given returns false only if one of the collection members is true
- [x] when a class is passed as an argument returns true if none of the collection is a member of such class
- [x] when a class is passed as an argument returns true if none of the collection is a member of such class::Numeric
- [x] when a class is passed as an argument returns false if any of the collection is a member of such class
- [x] when a Regex is passed as an argument returns true if none of the collection matches the Regex
- [x] when a Regex is passed as an argument returns false if any of the collection matches the Regex
- [x] when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern
- [ ] when a pattern other than Regex or a Class is given returns false only if one of the collection matches the pattern

### **my_count**
- [x] returns the number of items in enum through enumeration::range

### **my_map**
- [x] returns a new array with the results of running a given block once for every element in enum::range
- [x] returns an Enumerator if no block is given
- [x] executes only the proc when both a block and a proc are given and returns a new array with the results of running the proc once for every element in enum.

### **my_inject**
- [x] searches for the longest word in an array of strings
- [x] when a block is given without an initial value combines all elements of enum by applying a binary operation, specified by a block::range
- [x] when a block is given with an initial value combines all elements of enum by applying a binary operation, specified by a block
- [x]  when a symbol is specified without an initial value combines each element of the collection by applying the symbol as a named method
- [x] when a symbol is specified without an initial value combines each element of the collection by applying the symbol as a named method:range
- [x] when a symbol is specified with an initial value combines each element of the collection by applying the symbol as a named method
- [x] when a symbol is specified with an initial value combines each element of the collection by applying the symbol as a named method::range

Please fix the required changes and ask for another code review whenever you're ready

_**If you have any question related to the required changes feel free to text me on slack @GzimAsani** or just add a comment here_

HAPPY CODING :computer: :desktop_computer:

**Review by cyonii — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️✍️

Hello team, so far so good. You have worked really hard to implememt so much of the requested changes.

## To Improve

Kindly implement these changes below so that we can get this project approved.
You can reference this documentation on Ruby's enumerable and use the test cases. I believe this documentation will be great for your reference, [Documentation Here](https://ruby-doc.org/core-2.6.5/Enumerable.html).

- [x] Please rename your `my_enumerables.rb` file to `enumerables.rb` as this is what the automated test looks for.

**Failed tests:**

- [x] **`#my_any?`**
&dash; **context:** when no block or argument is given:
- [x] &emsp;&emsp;&mdash; it returns true if at least one of the collection is not false or nil
&dash; **context:** when a `Class` is passed as an argument
- [x] &emsp;&emsp;&mdash; it returns true if at least one of the collection is a member of such `Class`::`Numeric`
&dash; **context:** when a `Regex` is passed as an argument
- [x] &emsp;&emsp;&mdash; it returns true if any of the collection matches the Regex
&dash; **context:** when a pattern other than `Regex` or a `Class` is given
- [x] &emsp;&emsp;&mdash; it returns true if any of the collection matches the pattern
<br>

**`#my_none?`**
- [x] it returns true if the block never returns true for all elements
```ruby
let(:true_block) { proc { |num| num > 9 } }

it 'returns true if the block never returns true for all elements' do
    expect(array.my_none?(&true_block)).to eq(array.none?(&true_block))
end
```
- [x] it returns false if the block ever returns true for all elements
```ruby
let(:false_array) { [nil, false, nil, false] }

it 'returns false if the block ever returns true for all elements' do
    expect(array.my_none?(&false_block)).to eq(array.none?(&false_block))
end
```
- [x] it returns true only if none of the collection members is true
```ruby
let(:false_array) { [nil, false, nil, false] }

it 'returns true only if none of the collection members is true' do
    expect(false_array.my_none?).to be true
end
```

**`#my_map`**
- [x] it returns an `Enumerator` if no block is given
```ruby
it 'returns an Enumerator if no block is given' do
    expect([1, 3, 5, 'hello'].my_map).to be_an(Enumerator)
end
```

Please implement these changes and resubmit, happy coding.


>#### <br> You can find me on slack 👉 [CY Kalu](https://microverse-students.slack.com/team/U01494U96FR) if you need further assistance or clarification. I'm always available and will be glad to help.<br><br>

**Review by acushlakoncept — CHANGES_REQUESTED** [review]
# Status: Changes Required ♻️

### Hello @jmontanholi and @kiranitor123, Great job! 👏  Both of you have done well on this project.

You've done an awesome job so far 👌. But there are still some changes that are necessary for this project to be approved.


- [x] Kindly fix the linter errors on your PR

- [x] `#my_none?` should returns true if the block never returns true for all elements
```ruby
true_block = proc { |num| num > HIGHEST_VALUE }
expect(array.my_none?(&true_block)).to eq(array.none?(&true_block))
```

- [x] `#my_none?` returns false if the block ever returns true for all elements
```ruby
false_block = proc { |num| num <= HIGHEST_VALUE }
expect(array.my_none?(&false_block)).to eq(array.none?(&false_block))
```

- [x] `#my_none?` returns false if the block ever returns true for all elements
```ruby
%w[dog door rod blade].my_none?(5)
```

- [x] `#my_map` returns a new array with the results of running a given block once for every element in enum.
```ruby
expect(array.my_map { |num| num < 10 }).to eq(array.map { |num| num < 10 })
```

- [x] `#my_map` returns a new array with the results of running a given block once for every element in enum.
```ruby
expect(array.my_map(&block)).to eq array.map(&block)
```

- [x] `#my_map` returns a new array with the results of running a given block once for every element in enum::range
```ruby
expect(range.my_map(&block)).to eq range.map(&block)
```

- [x] `#my_map` accepts a proc as an argument and returns a new array with the results of running the proc once for every element in enum.
```ruby
expect(array.my_map(&my_proc)).to eq array.map(&my_proc)
```

- [x] `#my_map` executes only the proc when both a block and a proc are given and returns a new array with the results of running the proc once for every element in enum.
```ruby
expect(array.my_map(my_proc) { |num| num < 10 }).to eq array.map(&my_proc)
```

- [x] `#my_map` does not mutate the original array
```ruby
array.my_map { |num| num + 1 }
expect(array).to eq(array_clone)
```

- [x] `#my_inject` raises a "LocalJumpError" when no block or argument is
```ruby
expect { array.my_inject }.to raise_error(LocalJumpError)
```

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla) or reply to this thread, if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

**Review by jubaan — APPROVED** [review]

**Pull request merged**
